# Generated by Django 5.2 on 2025-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseach',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_field_name', models.CharField(blank=True, max_length=500, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('extraction_date', models.DateTimeField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('vi', 'vietnamese'), ('en', 'English')], default='vi', max_length=2)),
            ],
            options={
                'db_table': 'research',
            },
        ),
    ]
